version: "3"

services:
  backend:
    container_name: "crm_backend"
    build: backend
    restart: always
    ports:
      - "127.0.0.1:8777:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - crm_network

  postgres:
    image: postgres:13
    container_name: "crm_postgres"
    restart: always
    expose:
      - "5432"
    ports:
      - "127.0.0.1:54333:5432"
    env_file:
      - .env
    networks:
      - crm_network

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9777:9000"
      - "9778:9001"
    env_file:
      - .env
    volumes:
      - minio-storage:/data
    networks:
      - crm_network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data
    networks:
      - crm_network

volumes:
  minio-storage:
  redis:


networks:
  crm_network:
    name: crm_network
    driver: bridge
